well-known:
  issuer: https://autht.maerskline.com
  authorization_endpoint:  https://autht.maerskline.com/connect/authorize
  token_endpoint: https://autht.maerskline.com/connect/token
  token_endpoint_auth_methods_supported:
    - client_secret_basic
  token_endpoint_auth_signing_alg_values_supported:
    - RS256
    - ES256
    - DAS128
  userinfo_endpoint: https://autht.maerskline.com/connect/userinfo
  jwks_uri: https://autht.maerskline.com/connect/jwks.json
  registration_endpoint: https://autht.maerskline.com/connect/register
  scopes_supported:
    - openid
  response_types_supported:
    - token id_token
  acr_values_supported:
    - urn:mace:incommon:iap:silver
    - urn:mace:incommon:iap:bronze
  userinfo_signing_alg_values_supported:
    - RS256
    - ES256
    - HS256
  userinfo_encryption_alg_values_supported:
    - RSA1_5
    - A128KW
  userinfo_encryption_enc_values_supported:
    - A128CBC- HS256
    - A128GCM
  id_token_signing_alg_values_supported:
    - RS256
    - ES256
    - HS256
  id_token_encryption_alg_values_supported:
    - RSA1_5
    - A128KW
  id_token_encryption_enc_values_supported:
    - A128CBC- HS256
    - A128GCM
  request_object_signing_alg_values_supported:
    - none
    - RS256
    - ES256
  display_values_supported:
    - page
    - popup
  claim_types_supported:
    - normal
    - distributed
  claims_supported:
    - sub
    - iss
    - auth_time
    - acr
    - name
    - given_name
    - family_name
    - nickname
    - profile
    - picture
    - website
    - email
    - email_verified
    - locale
    - zoneinfo
    - http://example.info/claims/groups
  claims_parameter_supported: true

jwks:
  keys:
    -
      kty: RSA
      use: sig
      kid: B36D568F46A3AA89BA98FDFD73F99837D2A1C6D4
      x5t: B36D568F46A3AA89BA98FDFD73F99837D2A1C6D4
      n: DAE16A29280937DF4A9104A165F02AFE33DA53AB9F789C194DCC1E70A64F892458DEC8A557231464F05730ED279D8074D39447B806F4C5AD81D019C84962DC2E146E058687C1EE7B5AF298A15D3C41A4E1C4CB5A98CCD309A92A29C19795DC4C8ADDD0E8D9FB37496E15925CD2F8DC2414A359A1535B755BA6E3CE2E291F61CB245B19C91553FCD3CC36E3D95D303EE15DC95A38C8A5A011C1CD384DD34E8E3A4D17A483881349DCE19B4BE1BF649C25C0AC80C8913B5272C4B46773ACF248334FDAD6DBFDB17511CB4500CE064D5784AF5139F1447DFEB54A15E27697264143EA5736F2ADD2B2B14C29CAE39B6AEA4D2CE11FC95CD6CE0E3E6277C5ECA0DF3D4EAB7DF61A94814E9AE826062BD9EE416C4A1BB3F957DAA9DD883F7F91334FEBEE157DE7FB6B9C4352B1E85E933AE72971CB42BB8DAA41260611F5E9D491FF42345BBAA0E5DF0D690169C2D52FCA11C107A9B5F04912C1E82931F64FDFFF6208F4232919456C7E4BC747E1842E48DD866A7DF3987B886900810DBFC622ADD2DFD33910CD142105AE382B180AC906AD59EE84B5A9F2E4C47FA152DD1E3475A114315C0D12ECE4783D9C32E41F0065AB753210DD8B2AEFFE642196C71A09441CEB6590B9C98D1836F27745A5365723949D580E65EC384B3C8C3FF6C0CEB8D0B136D34E7C3751C0680F1CB5F4419E3E40CA3871CF86DB03D5957CB3B825029F7BF
      e: AQAB
      x5c:
        - MIIF8TCCA9mgAwIBAgIJAO9Cpleedb3dMA0GCSqGSIb3DQEBCwUAMIGOMQswCQYDVQQGEwJESzELMAkGA1UECAwCREsxEzARBgNVBAcMCkNvcGVuaGFnZW4xDzANBgNVBAoMBkRhc29qaTELMAkGA1UECwwCSVQxGTAXBgNVBAMMEGxvZ2luLmRhc29qaS5uZXQxJDAiBgkqhkiG9w0BCQEWFWJhbGEuZGFzb2ppQGdtYWlsLmNvbTAeFw0xNzEwMDgxMDQ5MTFaFw0xODEwMDgxMDQ5MTFaMIGOMQswCQYDVQQGEwJESzELMAkGA1UECAwCREsxEzARBgNVBAcMCkNvcGVuaGFnZW4xDzANBgNVBAoMBkRhc29qaTELMAkGA1UECwwCSVQxGTAXBgNVBAMMEGxvZ2luLmRhc29qaS5uZXQxJDAiBgkqhkiG9w0BCQEWFWJhbGEuZGFzb2ppQGdtYWlsLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANrhaikoCTffSpEEoWXwKv4z2lOrn3icGU3MHnCmT4kkWN7IpVcjFGTwVzDtJ52AdNOUR7gG9MWtgdAZyEli3C4UbgWGh8Hue1rymKFdPEGk4cTLWpjM0wmpKinBl5XcTIrd0OjZ+zdJbhWSXNL43CQUo1mhU1t1W6bjzi4pH2HLJFsZyRVT/NPMNuPZXTA+4V3JWjjIpaARwc04TdNOjjpNF6SDiBNJ3OGbS+G/ZJwlwKyAyJE7UnLEtGdzrPJIM0/a1tv9sXURy0UAzgZNV4SvUTnxRH3+tUoV4naXJkFD6lc28q3SsrFMKcrjm2rqTSzhH8lc1s4OPmJ3xeyg3z1Oq332GpSBTproJgYr2e5BbEobs/lX2qndiD9/kTNP6+4Vfef7a5xDUrHoXpM65ylxy0K7japBJgYR9enUkf9CNFu6oOXfDWkBacLVL8oRwQeptfBJEsHoKTH2T9//Ygj0IykZRWx+S8dH4YQuSN2Gan3zmHuIaQCBDb/GIq3S39M5EM0UIQWuOCsYCskGrVnuhLWp8uTEf6FS3R40daEUMVwNEuzkeD2cMuQfAGWrdTIQ3Ysq7/5kIZbHGglEHOtlkLnJjRg28ndFpTZXI5SdWA5l7DhLPIw/9sDOuNCxNtNOfDdRwGgPHLX0QZ4+QMo4cc+G2wPVlXyzuCUCn3v3AgMBAAGjUDBOMB0GA1UdDgQWBBRElPQQrMaymFlVCxk7GIld7rB/cTAfBgNVHSMEGDAWgBRElPQQrMaymFlVCxk7GIld7rB/cTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQBJA8Estn82kyvrZb7YPYZAmYXeoiVHd5Y0NhnWrOezj+H4M1nUnMQAFFvlXWfwA92Hz+paF50fLW2ugmsx/8eTUnv1/RpPa47A6FD/owUqG9ErzhcH+IGT+nklIT44dtSi+DgQTlOYMrdrnLwYp0gdnk0nCEL8pRy/YZoXr/Zgt0yOeK1haxtevRSC0ZKk3uiNy/wtQNYYosisdLUyulj1wKNGmwKYDxFsmS3+vpwuvmLx2/KVt5+cCOH8faE3Am6Br6Ms3Q9xsfAGm2O1944B1e4ZQMURcZgJSy5lV59scesaD0TZoNBttsg/kPiDCBvL7W4BMOB5D0d0aA6lYzXaVUJ9fa7dPumI7l9L7dwrMo3HbEpoQa8yM99d5e4RMf4Nz5LNv0grMFc9vpIFOIByjGtFqePdKDQWWICfZqOZq9H7idnfaCGpHgKTyccbzBwAsWzjzCenZZjwWe+mXJLf3AwwY+tTstivIamoWKcUTgU8o0RyRLL+rdFu11AUO4BdNYpvakEwK6ETJ9s+xuH1S+kFIS4q64A1GyYcc8kdmgeg+gK9nhH6RllSAZ+yM6hSItS6LOxj/xFV2oi2w6MryJGh1ZLlLa/HzN2yeXMFJHWecvOux81poTTf0rSehKagBrJ4vzjEANoJHybgKiJ2rLIc+KfTMCh49eM8edV8rA==

server:
    port: 8443
    ssl:
        key-store: classpath:keystore.p12
        key-store-password: zindagi
        keyStoreType: PKCS12
        keyAlias: tomcat
