well-known:
  issuer: https://login.maersk.com
  authorization_endpoint:  https://login.maersk.com/connect/authorize
  token_endpoint: https://login.maersk.com/connect/token
  token_endpoint_auth_methods_supported:
    - client_secret_basic
    - private_key_jwt
  token_endpoint_auth_signing_alg_values_supported:
    - RS256
    - ES256
    - DAS128
  userinfo_endpoint: https://login.maersk.com/userinfo
  jwks_uri: https://login.maersk.com/connect/jwks.json
  registration_endpoint: https://login.maersk.com/connect/register
  scopes_supported:
    - openid
    - profile
    - email
    - address
    - phone
    - offline_access
  response_types_supported:
    - code
    - code id_token
    - id_token
    - token id_token
  acr_values_supported:
    - urn:mace:incommon:iap:silver
    - urn:mace:incommon:iap:bronze
  userinfo_signing_alg_values_supported:
    - RS256
    - ES256
    - HS256
  userinfo_encryption_alg_values_supported:
    - RSA1_5
    - A128KW
  userinfo_encryption_enc_values_supported:
    - A128CBC- HS256
    - A128GCM
  id_token_signing_alg_values_supported:
    - RS256
    - ES256
    - HS256
  id_token_encryption_alg_values_supported:
    - RSA1_5
    - A128KW
  id_token_encryption_enc_values_supported:
    - A128CBC- HS256
    - A128GCM
  request_object_signing_alg_values_supported:
    - none
    - RS256
    - ES256
  display_values_supported:
    - page
    - popup
  claim_types_supported:
    - normal
    - distributed
  claims_supported:
    - sub
    - iss
    - auth_time
    - acr
    - name
    - given_name
    - family_name
    - nickname
    - profile
    - picture
    - website
    - email
    - email_verified
    - locale
    - zoneinfo
    - http://example.info/claims/groups
  claims_parameter_supported: true
