apiVersion: v1
kind: ReplicationController
metadata:
  name: ccp-web-rs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ccpweb
    spec:
      containers:
      - name: ccpwebcontainer
        image: gcr.io/dazzling-tensor-217/ccp-ui:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ccp-web-service
  labels:
    app: ccpweb
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ccpweb
