apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gclouddep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clouddasoji
    spec:
      containers:
      - name: hellodasoji
        image: gcr.io/dazzling-tensor-217/hidasoji-nginx
        ports:
        - name: nginx-port
          containerPort: 80
