apiVersion: v1
kind: Pod
metadata:
  name: nodehellodasoji.example.com
  labels:
    app: hellodasoji
spec:
  containers:
  - name: docker-demo
    image: baladasoji/docker-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
    env:
      -name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: db_secret
            key: username
      -name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db_secret
            key: password
