apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellosb-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hellospring
    spec:
      containers:
      - name: hellosb
        image: gcr.io/dazzling-tensor-217/hello-springboot:2.0
        ports:
        - name: httpport
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hellosb-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30409
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: hellospring
