version: '2'
services:
  web:
    image: "gcr.io/dazzling-tensor-217/ccp-ui"
    ports:
     - "80:8080"
  api:
    image: "gcr.io/dazzling-tensor-217/jwt-springsecurity" 
    ports:
     - "8888:8888"
