package com.maersk.booking;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.maersk.booking.Booking;
import com.maersk.booking.BookingRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/bookings") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private BookingRepository bookingRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewBooking (@RequestParam String customer , @RequestParam String source, @RequestParam String destination , @RequestParam String vessel ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Booking n = new Booking();
        n.setCustomer(customer);
        n.setSource(source);
        n.setDestination(destination);
        n.setVessel(vessel);
        bookingRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Booking> getAllBookings() {
        // This returns a JSON or XML with the users
        return bookingRepository.findAll();
    }
}
