package dbplay;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import dbplay.App;
import dbplay.AppRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private AppRepository appRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addApp (@RequestParam String name, @RequestParam String client_id , @RequestParam String client_secret, @RequestParam String redirect_uri ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        App app = new App();
        app.setName(name);
        app.setClient_id(client_id);
        app.setClient_secret(client_secret);
        app.setRedirect_uri(redirect_uri);
        appRepository.save(app);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<App> getAllApps() {
        // This returns a JSON or XML with the users
        return appRepository.findAll();
    }
}
